### ISSUE TITLE
utf-8 error online demo

### ISSUE THREAD

**Issue by jvail** [kripken/xml.js#10]
Any idea why validating ...

```xml
<?xml version="1.0"?>
<test>m²</test>
```

gives a parser error using the 'XML Text' input tab at http://syssgx.github.io/xml.js/ ?

```html
file.xml:2: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xB2 0x3C 0x2F 0x74
<test>mﾲ</test>
       ^
```

Thank you
Jan

**Comment by sterpe** [comment]
If you can validate the same with c-l tool, then I would say it must be some issue in the online demo text box.

**Comment by jvail** [comment]
Yes, you are right. I am able to both parse/validate it with xmllint cli and xml.js via node.

**Comment by sterpe** [comment]
Cool.  The demo site is maintained separately.  You may want to refile the bug with @syssgx.
