### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by jakedetels** [kripken/xml.js#12]
I'm getting the following error when trying to validate a large XML file (~ 100k lines):

> Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

It seems the solution is to modify the value of the TOTAL_MEMORY variable, but xml.js doesn't appear to expose any options for customizing that value.

**Comment by sterpe** [comment]
See if setting Module.TOTAL_MEMORY to some higher value directly after these lines in [./xmllint.js](./xmllint.js) works for you:

```

**Comment by jakedetels** [comment]
@sterpe: Thanks for the tip, I'll give it a try and report back.  I'm actually not using xml.js for client-side work, but XML validation on the server side with node.js.  I've tried some other xml packages for node.js, but I've found that xml.js is the easiest to use for our xml validation needs.

**Comment by sterpe** [comment]
Ok.  That makes sense.  If this doesn't work out I suppose you can shell out to actual xmllint if need be.

**Comment by jacobmischka** [comment]
Same problem here, the best option to me seems to just allow us to set it with options.TOTAL_MEMORY.
