### ISSUE TITLE
AVG virus alarm on windows 

### ISSUE THREAD

**Issue by sichvoge** [kripken/xml.js#17]
We are using xmllint inside our RAML JS parser and people report that they have issues with Windows and AVG reporting a virus coming from this library. See https://github.com/raml-org/raml-js-parser-2/issues/499#issuecomment-251722495.

Anyone still working on this project who can have a look please?

**Comment by sterpe** [comment]
This library is just a js compile of xmllint via emscripten so...feels like the error is AVG's.  I imagine there are no viruses in xmllint or in the output produced by emscripten.  @kripken

I would file a bug with AVG.

**Comment by sichvoge** [comment]
OK thanks!

**Comment by sichvoge** [comment]
We reported the issue back to AVG. Closing this.
