### ISSUE TITLE
Compiles, but no longer runs with emcc 1.29.0

### ISSUE THREAD

**Issue by sterpe** [kripken/xml.js#4]
Running the test fails after an apparently successful compile with emcc 1.29.0.

Attempted on both OS X & Ubuntu, same result.

On further investigation this appears to be related to a function pointer cast issue.

compiling with -s EMULATE_FUNCTION_POINTER_CASTS=1 seems to work.

**Comment by kripken** [comment]
We should probably add that to the build flags then (pull request welcome). I wonder though why this changed. Which version worked before?

**Comment by sterpe** [comment]
Not sure, I found your blog with instructions here:

http://mozakai.blogspot.com/2012/03/howto-port-cc-library-to-javascript.html
And these here: 
https://github.com/jallwine/emscripten_test/wiki/Getting-Started-With-Emscripten

Both of which are over 2.5 years old.

I think I've more or less tracked this down to the casting of functions to (xmlHashScanner) defined in libxml2/nclude/libxml/hash.c which is a viii signature.

**Comment by sterpe** [comment]
In the past did emcc **emulate** function pointer casts?

**Comment by kripken** [comment]
In the far past, I guess maybe 2.5 is enough ;), we did function pointers differently, and it could explain this.

**Comment by sterpe** [comment]
Mind if I replace ./build.sh with a gulp file ?

**Comment by kripken** [comment]
What is gulp? :)

**Comment by sterpe** [comment]
Node streaming build tool...In this case it would probably just end up child_process.exec'ing shell commands to launch emcc etc.  I'll try it out on my fork and if it seems pointless I won't bother.

http://slides.com/contra/gulp#/

**Comment by rajashekhargundeti** [comment]
with the latest build, i dont have any issues as the flag is already part of it.

I looked at script/test file. it is using emcc library to build xmllint-test.js file along with .mem file. 
I wonder how i could use this in my project since it needs emcc library and its dependencies need to be part of box, which is sometimes not possible.
